### ISSUE TITLE
Failed to communicate with MPRLS sensor, check wiring?

### ISSUE THREAD

**Issue by ncm7** [adafruit/Adafruit_MPRLS#10]
I have an Adafruit MPRLS sensor and it is well connected with
Arduino to get some pressure readings.
The serial monitor says: 
-> MPRLS Simple Test
-> Failed to communicate with MPRLS sensor, check wiring?
I am using the Adafruit MPRLS library and mprls_simplest code.
I have followed the following page to arrange the circuit and the library
[https://learn.adafruit.com/adafruit-mpr ... duino-test](https://learn.adafruit.com/adafruit-mprls-ported-pressure-sensor-breakout/arduino-test)

Please, let me know how can I fix this issue.

**Comment by caternuson** [comment]
See here:
https://forums.adafruit.com/viewtopic.php?f=19&t=192074

**Comment by ncm7** [comment]
Hey, it's me over there too. I posted it. I am getting a good response, Thank you!

**Comment by raevillena** [comment]
This happened to us too even with very good wiring/solder
