### ISSUE TITLE
The begin() function is misleading.

### ISSUE THREAD

**Issue by uodukwe** [adafruit/Adafruit_MPRLS#2]
In the .h file (Adafruit_MPRLS.h) at line 44 & 45, the begin()  function has two arguments: uint8_t i2c_addr and TwoWire *twoWire.

I also see they were assigned: 
i2c_addr  is assigned to MPRLS_DEFAULT_ADDR
and
twoWire is de-referenced to Wire. Where is this 'Wire' defined or instantiated?
My common sense says it's from 'Wire.h'

**Comment by ladyada** [comment]
yes - it comes with Arduino. 
https://github.com/adafruit/Adafruit_MPRLS/blob/master/Adafruit_MPRLS.cpp#L59
