### ISSUE TITLE
Speed up the sensor readings

### ISSUE THREAD

**Issue by LawrenceGeafer** [adafruit/Adafruit_MPRLS#4]
- Arduino board:  Arduino Uno
- Arduino IDE version 1.8.13

Hi,

I found, that my code runs quite slow, when using the MPRLS library and reading from the sensor. I reported this issue in the Adafruit customers forum, see:
https://forums.adafruit.com/viewtopic.php?f=19&t=167853

In short, I was not able to read data from the sensor more than around 66 times per second (66Hz), although the sensors datasheet claims up to 200Hz. 

The problem comes from the file "Adafruit_MPRLS.cpp", where the function "readData(void)" contains these lines:

// Use the gpio to tell end of conversion
if (_eoc != -1) {
while (!digitalRead(_eoc)) {
**delay(10);**
}
} else {
// check the status byte
uint8_t stat;
while ((stat = readStatus()) & MPRLS_STATUS_BUSY) {
// Serial.print("Status: "); Serial.println(stat, HEX);
**delay(10);**
}
}

Deleting the delays nearly doubled the speed of my readings to 125Hz. This is not as fast as advertised (I think you have to make use of the EOC-pin to become faster) but still a significant performance gain. 

I suggest deleting the delays.

Thanks,

Larry

**Comment by ladyada** [comment]
thanks, want to try submitting a PR with that change?

**Comment by LawrenceGeafer** [comment]
Yes, give me a day or two.

**Comment by LawrenceGeafer** [comment]
Did starting the pull request work? I'm new to github and I'm not sure if I've done everyting correctly.

**Comment by ladyada** [comment]
yep great! :) thanx!
