### ISSUE TITLE
Potential for getting stuck in while loops

### ISSUE THREAD

**Issue by stephenf7072** [adafruit/Adafruit_MPRLS#6]
There are two while loops in readData() which can turn into forever-loops if hardware is disconnected or things otherwise don't go as expected.  Can I suggest adding a count variable, and something like this code inside each loop:

`count++;
delay(1);
if(count>100)	//Frozen or something
  return 0xFFFFFFFF;	//Error`

**Comment by ladyada** [comment]
sure you can add a timeout, however if hardware is disconnected you will probably hang on the i2c reads anyways

**Comment by stephenf7072** [comment]
I wondered that too, but I've tested it (albeit only on Apollo3 based uC) and with the extra code, it doesn't hang with hardware disconnected.  I can make a pull request if useful, otherwise no worries and we can close the issue.

**Comment by arkhipenko** [comment]
This should be resolved by the #7 if approved and merged.

**Comment by stephenf7072** [comment]
Nice one, cheers.

**Comment by arkhipenko** [comment]
@stephenf7072 the PR was merged, please test and close this issue if you are OK with the change

**Comment by stephenf7072** [comment]
Looks good (apologies, I don't have any opportunity to test for the moment), issue closed.

**Comment by ladyada** [comment]
thanks :)
