### ISSUE TITLE
Convert to BusIO

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_MPRLS#8]
https://github.com/adafruit/Adafruit_BusIO

**Comment by aryangupta0405** [comment]
Hey, I have MPRLS0300YG00001B which is 0-300mmhg & the 'B' means a transfer function of 2.5% to 22.5%, what changes should I make to work perfectly

**Comment by caternuson** [comment]
@aryangupta0405 see section 8 of the datasheet for details:
https://prod-edam.honeywell.com/content/dam/honeywell-edam/sps/siot/en-us/products/sensors/pressure-sensors/board-mount-pressure-sensors/micropressure-mpr-series/documents/sps-siot-mpr-series-datasheet-32332628-ciid-172626.pdf

This issue has nothing to do with supporting different sensor variants. Please start a new issue.

**Comment by arkhipenko** [comment]
@aryangupta0405 The library was specifically implemented to take what you listed as constructor parameters:

```
  Adafruit_MPRLS(int8_t reset_pin = -1, int8_t EOC_pin = -1,
                 uint16_t PSI_min = 0, uint16_t PSI_max = 25,
                 float OUTPUT_min = 10, float OUTPUT_max = 90,
                 float K = PSI_to_HPA);
```

Just convert your 300 mm to PSI and supply parameters to the constructor - should work.

**Comment by caternuson** [comment]
done with #9
